apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawl-submission
spec:
  schedule: "0/30 0-20/1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 1
      completions: 1
      ttlSecondsAfterFinished: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: crawl-submission-batch
              image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.3.3
              imagePullPolicy: Always
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: db-auth
                      key: database-url-master
                - name: SOLR_HOST
                  value: http://solr-0.solr-headless:8983
                - name: PGSSLMODE
                  value: disable
                - name: ATCODER_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: atcoder-auth
                      key: atcoder-username
                - name: ATCODER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: atcoder-auth
                      key: atcoder-password
              resources:
                requests:
                  memory: 64Mi
                  cpu: 50m
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
              args:
                - atcodersearch
                - crawl
                - submission
                - --duration=3s
                - --retry=10
          imagePullSecrets:
            - name: regcred
