apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-user
spec:
  schedule: "0 3 * * 0,1"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 1
      completions: 1
      ttlSecondsAfterFinished: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: update-user-batch
              image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.3.2
              imagePullPolicy: Always
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: db-auth
                      key: database-url-master
                - name: SOLR_HOST
                  value: http://solr-0.solr-headless:8983
                - name: PGSSLMODE
                  value: disable
              resources:
                requests:
                  memory: 64Mi
                  cpu: 50m
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
              args:
                - atcodersearch
                - update
                - user
                - --optimize
          imagePullSecrets:
            - name: regcred
