apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:3.0-debug
          env:
            - name: TZ
              value: Asia/Tokyo
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: var-log
              mountPath: /var/log
            - name: var-lib-docker-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: config
              mountPath: /fluent-bit/etc/parsers.conf
              subPath: parsers.conf
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-lib-docker-containers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: fluentbit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File /fluent-bit/etc/parsers.conf

    # Backend
    [INPUT]
        Name              tail
        Path              /var/log/containers/*_backend-*.log
        Parser            docker
        Tag               backend
        Refresh_Interval  5
        Read_from_Head    true
        DB                /var/log/backend.log.pos
    [FILTER]
        Name                parser
        Match               backend
        Key_Name            log
        Parser              json
    [OUTPUT]
        Name   stdout
        Match  backend

  parsers.conf: |
    [PARSER]
      Name        docker
      Format      regex
      Regex       ^(?<kubetime>[^ ]*) (?<stream>stdout|stderr) . (?<log>.*)$
      Time_Key    kubetime
      Time_Format %Y-%m-%dT%H:%M:%S.%L
      Time_Keep   On

    [PARSER]
      Name            json
      Format          json
      Time_Key        time
      Time_Format     %Y-%m-%dT%H:%M:%S.%L%z
      Time_Keep       On
      Decode_Field_As escaped_utf8 log
      Decode_Field_As escaped log
