services:
  postgresql:
    image: postgres:16-bullseye
    container_name: atcodersearch-postgresql
    environment:
      POSTGRES_PASSWORD: atcodersearch
      POSTGRES_USER: atcodersearch
      POSTGRES_DB: atcodersearch
      POSTGRES_HOST_AUTH_METHOD: password
      TZ: "Asia/Tokyo"
    volumes:
      - type: volume
        source: atcodersearch-postgresql
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      atcodersearch-net:

  meilisearch:
    image: getmeili/meilisearch:prototype-japanese-184
    container_name: atcodersearch-meilisearch
    environment:
      - MEILI_MASTER_KEY=meili-master-key
      - MEILI_LOG_LEVEL=DEBUG
    # volumes:
    #   - type: volume
    #     source: atcodersearch-meilisearch
    #     target: /meili_data
    ports:
      - 7700:7700
    networks:
      atcodersearch-net:

networks:
  atcodersearch-net:

volumes:
  atcodersearch-postgresql:
  atcodersearch-meilisearch:
