services:
  postgresql:
    image: postgres:16-bullseye
    container_name: atcodersearch-postgres
    environment:
      POSTGRES_PASSWORD: atcodersearch
      POSTGRES_USER: atcodersearch
      POSTGRES_DB: atcodersearch
      POSTGRES_HOST_AUTH_METHOD: password
      TZ: "Asia/Tokyo"
    volumes:
      - type: volume
        source: atcodersearch-postgres
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      atcodersearch-net:

networks:
  atcodersearch-net:

volumes:
  atcodersearch-postgres:
