services:
  test-db:
    image: postgres:15-bullseye
    container_name: atcodersearch-test-postgres
    environment:
      POSTGRES_PASSWORD: atcodersearch
      POSTGRES_USER: atcodersearch
      POSTGRES_DB: atcodersearch
      POSTGRES_HOST_AUTH_METHOD: password
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: ./backend/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
    ports:
      - 15432:5432
    networks:
      atcodersearch-test-net:
  test-solr:
    image: atcodersearch-solr
    container_name: atcodersearch-test-solr
    build:
      context: middlewares/solr
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: middlewares/solr/problems/conf
        target: /var/solr/data/problems/conf
      - type: bind
        source: middlewares/solr/solutions/conf
        target: /var/solr/data/solutions/conf
      - type: bind
        source: middlewares/solr/users/conf
        target: /var/solr/data/users/conf
    ports:
      - 18983:8983
    networks:
      atcodersearch-test-net:

networks:
  atcodersearch-test-net:
