// Code generated by MockGen. DO NOT EDIT.
// Source: language.go
//
// Generated by this command:
//
//	mockgen -source=language.go -destination=./mock/mock_language.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	repository "fjnkt98/atcodersearch/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLanguageRepository is a mock of LanguageRepository interface.
type MockLanguageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageRepositoryMockRecorder
}

// MockLanguageRepositoryMockRecorder is the mock recorder for MockLanguageRepository.
type MockLanguageRepositoryMockRecorder struct {
	mock *MockLanguageRepository
}

// NewMockLanguageRepository creates a new mock instance.
func NewMockLanguageRepository(ctrl *gomock.Controller) *MockLanguageRepository {
	mock := &MockLanguageRepository{ctrl: ctrl}
	mock.recorder = &MockLanguageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageRepository) EXPECT() *MockLanguageRepositoryMockRecorder {
	return m.recorder
}

// FetchLanguageGroups mocks base method.
func (m *MockLanguageRepository) FetchLanguageGroups(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLanguageGroups", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLanguageGroups indicates an expected call of FetchLanguageGroups.
func (mr *MockLanguageRepositoryMockRecorder) FetchLanguageGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLanguageGroups", reflect.TypeOf((*MockLanguageRepository)(nil).FetchLanguageGroups), ctx)
}

// FetchLanguages mocks base method.
func (m *MockLanguageRepository) FetchLanguages(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLanguages", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLanguages indicates an expected call of FetchLanguages.
func (mr *MockLanguageRepositoryMockRecorder) FetchLanguages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLanguages", reflect.TypeOf((*MockLanguageRepository)(nil).FetchLanguages), ctx)
}

// Save mocks base method.
func (m *MockLanguageRepository) Save(ctx context.Context, languages []repository.Language) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, languages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLanguageRepositoryMockRecorder) Save(ctx, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLanguageRepository)(nil).Save), ctx, languages)
}
