database_url: ""
table_schema: ""
solr_host: "http://localhost:8983"
atcoder_username: ""
atcoder_password: ""
trusted_proxies:
  - "127.0.0.1"
do_migrate: false
problem_core_name: "problem"
user_core_name: "user"
submission_core_name: "submission"
crawl:
  problem:
    duration: 3000
    all: false
  user:
    duration: 1000
  submission:
    duration: 3000
    retry: 5
    targets:
      - "ABC"
      - "ABC-Like"
      - "ARC"
      - "ARC-Like"
      - "AGC"
      - "AGC-Like"
      - "JOI"
      - "Other Sponsored"
      - "PAST"
generate:
  problem:
    save_dir: "/var/tmp/atcoder/problem"
    concurrent: 2
    chunk_size: 1000
  user:
    save_dir: "/var/tmp/atcoder/user"
    concurrent: 2
    chunk_size: 10000
  submission:
    save_dir: "/var/tmp/atcoder/submission"
    concurrent: 2
    chunk_size: 10000
    interval: 90
    all: false
upload:
  problem:
    save_dir: "/var/tmp/atcoder/problem"
    concurrent: 2
    optimize: false
    truncate: false
  user:
    save_dir: "/var/tmp/atcoder/user"
    concurrent: 2
    optimize: false
    truncate: false
  submission:
    save_dir: "/var/tmp/atcoder/submission"
    concurrent: 2
    optimize: false
    truncate: false
update:
  problem:
    skip_fetch: false
  user:
    skip_fetch: false
