apiVersion: batch/v1
kind: Job
metadata:
  name: one-shot-problem-indexer
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: problem-indexer
          image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.1.5
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-backend
                  key: database-url
            - name: SOLR_HOST
              value: http://solr:8983
            - name: DOCUMENT_SAVE_DIRECTORY
              value: /var/tmp
            - name: PGSSLMODE
              value: disable
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          args:
            [
              "atcodersearch",
              "update",
              "problem",
              "--all",
              "--migrate",
              "--optimize",
              "--generate-concurrent=2",
              "--post-concurrent=2",
              "--duration=1000",
              "--chunk-size=1000",
            ]
