apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:develop
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: postgres://atcodersearch:atcodersearch@postgresql-0.postgresql-headless:5432/atcodersearch?sslmode=disable
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          command:
            - atlas
            - schema
            - apply
            - --url
            - $(DATABASE_URL)
            - --to
            - file:///etc/schema.hcl
            - --auto-approve
      imagePullSecrets:
        - name: regcred
