---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: frontend
          image: atcodersearch-frontend:0.1.0
          imagePullPolicy: Never
          ports:
            - name: frontend
              containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
