---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: problem-indexer
spec:
  schedule: "0 10 * * 0"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: indexer
              image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.1.2
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secret-backend
                      key: database-url
                - name: SOLR_HOST
                  value: http://solr:8983
                - name: DOCUMENT_SAVE_DIRECTORY
                  value: /var/tmp
                - name: PGSSLMODE
                  value: disable
              resources:
                requests:
                  memory: 1024Mi
                  cpu: 1000m
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
              args:
                [
                  "atcodersearch",
                  "update",
                  "problem",
                  "--migrate",
                  "--optimize",
                  "--generate-concurrent=2",
                  "--post-concurrent=2",
                  "--duration=1000",
                  "--chunk-size=1000",
                ]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-indexer
spec:
  schedule: "0 11 * * 0"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: indexer
              image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.1.2
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secret-backend
                      key: database-url
                - name: SOLR_HOST
                  value: http://solr:8983
                - name: DOCUMENT_SAVE_DIRECTORY
                  value: /var/tmp
                - name: PGSSLMODE
                  value: disable
              resources:
                requests:
                  memory: 512Mi
                  cpu: 500m
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
              args:
                [
                  "atcodersearch",
                  "update",
                  "user",
                  "--migrate",
                  "--optimize",
                  "--generate-concurrent=2",
                  "--post-concurrent=2",
                  "--duration=1000",
                  "--chunk-size=10000",
                ]
          imagePullSecrets:
            - name: regcred

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: submission-indexer
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: indexer
              image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.1.2
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secret-backend
                      key: database-url
                - name: SOLR_HOST
                  value: http://solr:8983
                - name: DOCUMENT_SAVE_DIRECTORY
                  value: /var/tmp
                - name: PGSSLMODE
                  value: disable
              resources:
                requests:
                  memory: 512Mi
                  cpu: 500m
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
              args:
                [
                  "atcodersearch",
                  "update",
                  "submission",
                  "--migrate",
                  "--generate-concurrent=2",
                  "--post-concurrent=2",
                  "--chunk-size=10000",
                ]
          imagePullSecrets:
            - name: regcred
