---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "solr"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:15-bullseye
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: database
            - name: POSTGRES_HOST_AUTH_METHOD
              value: password
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
          args:
            [
              "postgres",
              "-c",
              "shared_buffers=256MB",
              "-c",
              "checkpoint_timeout=30min",
              "-c",
              "checkpoint_completion_target=0.9",
              "-c",
              "max_wal_size=20GB",
              "-c",
              "log_timezone=Asia/Tokyo",
              "-c",
              "timezone=Asia/Tokyo",
            ]
      initContainers:
        - name: chown-data-directory
          image: busybox:1.28
          command: ["/bin/chown", "-R", "999:999", "/var/lib/postgresql/data"]
          securityContext:
            runAsNonRoot: false
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
        - name: chmod-data-directory
          image: busybox:1.28
          command: ["/bin/chmod", "-R", "0750", "/var/lib/postgresql/data"]
          securityContext:
            runAsNonRoot: false
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
