apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
spec:
  selector:
    matchLabels:
      app: meilisearch
  serviceName: meilisearch-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:prototype-japanese-184
          env:
            - name: MEILI_MASTER_KEY
              value: engine-master-key
          ports:
            - containerPort: 7700
              name: meilisearch
          volumeMounts:
            - name: meilisearch-pvc
              mountPath: /meili_data
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          args:
            - /bin/meilisearch
            - --experimental-logs-mode=json
  volumeClaimTemplates:
    - metadata:
        name: meilisearch-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
