apiVersion: batch/v1
kind: Job
metadata:
  name: one-shot-crawl-submission
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: crawl-submission-batch
          image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:develop
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: postgres://atcodersearch:atcodersearch@postgresql-0.postgresql-headless:5432/atcodersearch?sslmode=disable
            - name: SOLR_HOST
              value: http://solr-0.solr-headless:8983
            - name: PGSSLMODE
              value: disable
            - name: ATCODER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: atcoder-auth
                  key: atcoder-username
            - name: ATCODER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atcoder-auth
                  key: atcoder-password
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          args:
            - atcodersearch
            - crawl
            - submission
            - --duration=5s
            - --retry=5
            - --target=ABC
      imagePullSecrets:
        - name: regcred
