apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  selector:
    matchLabels:
      app: solr
  serviceName: solr-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: solr
    spec:
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        runAsNonRoot: true
        fsGroup: 8983
      terminationGracePeriodSeconds: 60
      containers:
        - name: solr
          image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-solr:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8983
              name: solr
          env:
            - name: SOLR_JAVA_MEM
              value: "-Xms1024m -Xmx1024m"
          resources:
            limits:
              memory: 2048Mi
              cpu: 1000m
          volumeMounts:
            - name: problems-pvc
              mountPath: /var/solr/data/problems/data
            - name: users-pvc
              mountPath: /var/solr/data/users/data
            - name: solutions-pvc
              mountPath: /var/solr/data/solutions/data
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: problems-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
    - metadata:
        name: users-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
    - metadata:
        name: solutions-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
