openapi: 3.0.0
info:
  title: AtCoder Search Backend API
  description: AtCoder Search backend API
  version: 0.1.0
paths:
  /api/search:
    get:
      summary: Search problems with query parameter
      description: Search problems
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: The search keyword.
          required: false
        - in: query
          name: c
          schema:
            type: integer
            minimum: 0
            maximum: 200
            default: 20
          description: The number of search results per page.
          required: false
        - in: query
          name: p
          schema:
            type: integer
            minimum: 1
            default: 1
          description: The page index of search results.
          required: false
        - in: query
          name: f[category][]
          schema:
            type: array
            items:
              type: string
          example: "ABC"
          description: Multiple values are accepted. Set the value in the f[category][] key for each value.
          explode: true
        - in: query
          name: f[difficulty][from]
          schema:
            type: integer
          example: 1000
        - in: query
          name: f[difficulty][to]
          schema:
            type: integer
          example: 2000
        - in: query
          name: s
          schema:
            type: string
            enum:
              - "start_at"
              - "-start_at"
              - "difficulty"
              - "-difficulty"
              - "-score"
            default: -score
      responses:
        200:
          description: "Search result"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
    post:
      summary: Search problems with json request
      description: Search problems with json request
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                c:
                  type: integer
                  minimum: 0
                  maximum: 200
                  default: 20
                p:
                  type: integer
                  minimum: 1
                  default: 1
                s:
                  type: string
                  enum:
                    - "start_at"
                    - "-start_at"
                    - "difficulty"
                    - "-difficulty"
                    - "-score"
                  default: -score
                f:
                  type: object
                  properties:
                    category:
                      type: array
                      items:
                        type: string
                    difficulty:
                      type: object
                      properties:
                        from:
                          type: integer
                        to:
                          type: integer
      responses:
        200:
          description: "Search result"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
components:
  schemas:
    # ------------------
    # 検索結果の統計情報
    # ------------------
    Stats:
      type: object
      properties:
        # 検索処理時間
        time:
          type: integer
        # 総検索ヒット数
        total:
          type: integer
        # 表示ページ番号
        index:
          type: integer
        # 総ページ数
        pages:
          type: integer
        # 返却件数
        count:
          type: integer
        # ファセット情報
        facet:
          type: object
      required:
        - time
        - total
        - index
        - pages
        - count
    # -----------------------
    # ドキュメント
    # -----------------------
    Items:
      type: object
      properties:
        problem_id:
          type: string
        problem_title:
          type: string
        problem_url:
          type: string
          format: uri
        contest_id:
          type: string
        contest_title:
          type: string
        contest_url:
          type: string
          format: uri
        difficulty:
          type: integer
        start_at:
          type: string
          format: date-time
        duration:
          type: integer
        rate_change:
          type: string
        category:
          type: string
    # ----------------------------
    # 検索結果のレスポンス(正常時)
    # ----------------------------
    SearchResponse:
      type: object
      properties:
        stats:
          type: object
          $ref: "#/components/schemas/Stats"
        items:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/Items"
        message:
          type: string
      required:
        - stats
        - items
