apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: backend
          image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.4.7
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: database-url
            - name: ENGINE_URL
              value: http://meilisearch-0.meilisearch-headless:7700
            - name: ENGINE_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: engine-auth
                  key: engine-master-key
            - name: BACKEND_PORT
              value: "8000"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m
          ports:
            - name: backend
              containerPort: 8000
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          args:
            - atcodersearch
            - serve
      imagePullSecrets:
        - name: regcred
