apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: backend
          image: 999441754240.dkr.ecr.ap-northeast-1.amazonaws.com/atcodersearch-backend:0.3.3
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: database-url
            - name: SOLR_HOST
              value: http://solr:8983
            - name: ALLOW_ORIGIN
              value: "https://atcoder-search.fjnkt98.com"
            - name: PORT
              value: "8000"
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m
          ports:
            - name: backend
              containerPort: 8000
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          args:
            - atcodersearch
            - serve
      imagePullSecrets:
        - name: regcred
