export const colors = new Map<string, string>([
  ["ABC", "bg-blue-500"],
  ["ABC-Like", "bg-sky-600"],
  ["AGC", "bg-yellow-600"],
  ["AGC-Like", "bg-amber-500"],
  ["AHC", "bg-green-500"],
  ["ARC", "bg-red-500"],
  ["ARC-Like", "bg-orange-700"],
  ["JAG", "bg-slate-500"],
  ["JOI", "bg-slate-600"],
  ["Marathon", "bg-slate-600"],
  ["Other Contests", "bg-slate-600"],
  ["Other Sponsored", "bg-slate-600"],
  ["PAST", "bg-slate-600"],
  ["black", "bg-gray-900"],
  ["gray", "bg-gray-500"],
  ["brown", "bg-amber-800"],
  ["green", "bg-green-500"],
  ["cyan", "bg-cyan-400"],
  ["blue", "bg-blue-600"],
  ["yellow", "bg-yellow-300"],
  ["orange", "bg-orange-400"],
  ["red", "bg-red-600"],
  ["silver", "bg-zinc-400"],
  ["gold", "bg-amber-400"],
]);
