name: grant-tag-backend
run-name: grant-tag-backend
on:
  push:
    branches:
      - master
    paths:
      - backend/VERSION
jobs:
  grant-tag-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-atcodersearch-backend-version
        with:
          create-tag: false
          version-command: cat backend/VERSION
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.detect-atcodersearch-backend-version.outputs.current-version}}
          tag_prefix: "atcodersearch-backend_v"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
