name: grant-tag-solr
run-name: grant-tag-solr
on:
  push:
    branches:
      - master
    paths:
      - middlewares/solr/VERSION
jobs:
  grant-tag-solr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-atcodersearch-solr-version
        with:
          create-tag: false
          version-command: |
            cat middlewares/solr/VERSION
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.detect-atcodersearch-solr-version.outputs.current-version}}
          tag_prefix: "atcodersearch-solr_v"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
