name: publish-image-solr-dev
run-name: publish-image-solr-dev
on:
  push:
    branches:
      - develop
    paths:
      - middlewares/solr/**
env:
  BUILD_CONTEXT: middlewares/solr
  ECR_REPOSITORY: atcodersearch-solr
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ env.BUILD_CONTEXT }}"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
