name: test
run-name: test
on:
  push:
    branches:
      - develop
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run test
        run: make test
