name: test-backend
run-name: test-backend
on:
  pull_request:
    paths:
      - backend/**
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install sqlc
        run: go install -v github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0

      - name: Install ogen
        run: go install -v github.com/ogen-go/ogen/cmd/ogen@v1.5.0

      - name: Run test
        run: make test
